apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    name: docker-registry
  ports:
    - protocol: TCP
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
spec:
  selector:
    name: docker-registry-ui
  ports:
    - protocol: TCP
      port: 80

