apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: docker-registry-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: images.hidden.computer
    http:
      paths:
      - path: /v2/.*
        backend:
          serviceName: docker-registry
          servicePort: 5000
      - path: /
        backend:
          serviceName: docker-registry-ui
          servicePort: 80

